pipeline{
    agent any
    stages{
        stage('verify branch'){
            steps{
                echo "$GIT_BRANCH"
            }
        }
        stage('Docker Build'){
            steps{
                powershell(script: 'ls')
                // pwsh(script: 'docker images -a')
                // pwsh(script: 'echo "after docker images command "')
                // pwsh(script: """
                // cd Jenkins/azure-voting-app-redis/azure-vote/
                // ls
                // docker images -a
                // docker build -t jenkins-pipeling .
                // docker images -a
                // cd ..
                // """)
            }
        }
    }
}
